trigger:
  branches:
    include:  
    - main
variables:
  - group: default_credentials
parameters:
  - name: variable_check
    type: boolean
    displayName: "variablecheck default false"
    default: false
stages:
  - template: stages/versioncheck.yml
    parameters:
      variable_check: ${{ parameters.variable_check }}
