trigger:
  branches:
    include:  
    - main
variables:
  - group: default_credentials
  - name: azureSubcriptionEndpoint
    value: github
  - name: azureSubcriptionEndpoint
    value: docker-hub
stages:
  - stage: version checking
    displayName: "version checking"
    jobs:
      - job: version_check
        displayName: "version_check" 
        pool:
          name: wsl
        workspace: 
          clean: all
        steps:
          - bash: |
              echo "version checking"
              git --version
            displayName: "git version checking"
