trigger:
  branches:
    include:  
    - main
variables:
  - group: default_credentials
stages:
  - stage: version_checking
    displayName: "version checking"
    jobs:
      - job: versioncheck
        displayName: "versioncheck" 
        pool:
          name: wsl
        workspace: 
          clean: all
        steps:
          - bash: |
              echo "version checking"
              git --version
            displayName: "git version checking"
      
      - job: variablecheck
        dependsOn: versioncheck
        displayName: "variablecheck" 
        pool:
          name: wsl
        workspace: 
          clean: all
        steps:
          - bash: |
              echo "variable checking"
              echo "$(GIT_USER)"
               echo "$(DOCKER_USER)"
            displayName: "git variable checking"
            env: 
              GIT_USER: $(github_user)
              DOCKER_USER: $(docker_user)
