trigger:
  branches:
    include:  
    - main
variables:
  - group: default_credentials
parameters:
  - name: variable_check
    type: boolean
    displayName: "variablecheck default false"
    default: false
stages:
  - template: templates/stages/versioncheck.yml
  - ${{ if eq( parameters.variable_check, true ) }}:
    - template: templates/stages/variablecheck.yml
      parameter:
       variable_check: ${{ parameters.variable_check }}
